### PR TITLE
Use NameAllocator for adapter fields, locals

### LINKED ISSUE #20: Use NameAllocator for adapter fields, locals.
Currently any object with a property named "writer", "value", "OPTIONS", "reader", or "adapterN" (where N is a digit) is going to create code that will fail to compile.

The way we like to do this is by allocating all the names up front starting with the constants and then moving on to the user properties. You can use things like the property object as a key so that later you can ask the name allocator what the local for that property is without carting around strings.

Example: 
https://github.com/square/wire/blob/d48be72904d7f6e1458b762cd936b1a7069c2813/wire-java-generator/src/main/java/com/squareup/wire/java/JavaGenerator.java#L152-L180

### PR DESCRIPTION
**Pull request by ansman**
This closes #20

### CODE REVIEW

**Comment by ansman** [comment]
@JakeWharton Could you please review this one.

File: compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt [hunk 1]
```diff
@@ -91,6 +92,15 @@ class AdaptersProcessingStep(
...
                 ?: emptyList()
 
+        nameAllocator.newName("OPTIONS")
+        nameAllocator.newName("value")
+        nameAllocator.newName("writer")
+        nameAllocator.newName("reader")
+        nameAllocator.newName("types")
+        nameAllocator.newName("moshi")
+        nameAllocator.newName("stringBuilder")
+        (0 until adapterKeys.size).forEach { nameAllocator.newName(generateAdapterFieldName(it)) }
```
Comment (ansman) [inline compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt]: Perhaps we should actually use the return values here but all of them are valid java identifiers and it just seemed easier to reserve them.
